### ISSUE TITLE
Decide on Backend Implementation - [1]

### ISSUE THREAD

**Issue by ryankarch** [sdd-lams/learning-assistant-management-system#21]

**Comment by carterelseif** [comment]
MongoDB can be used to create custom user roles (LA role) while using Firebase to handle authentication. Firebase will handle the username/email signup and login. Firebase will then return a token for the user (which we can use as a userid) and then we can store that ID in MongoDB as a user entry and we can create a custom role for users that has very granular permissions on documents that we define in MongoDB (using the Atlas tool probably).

https://www.mongodb.com/docs/atlas/app-services/rules/
